### ISSUE TITLE
enable-usermedia-screen-capturing no longer available

### ISSUE THREAD

**Issue by AntoineWtrnd** [mgechev/jscapture#13]
Google Chrome –enable-usermedia-screen-capturing flag was available in previous versions of Chrome, which allows content and screen sharing as an experimental basis among all Chrome users. A Chrome user could enable “screen capture support in getUserMedia()” by visiting ‘chrome://flags’. However, in the later versions of Chrome, the feature is not available and the flag “enable screen capture support in getUserMedia()” is no more available.

**Comment by mgechev** [comment]
https://github.com/mgechev/jscapture#warning
