### ISSUE TITLE
Hi Team, good job you have done.

### ISSUE THREAD

**Issue by rajamohamedbarook** [mgechev/jscapture#8]
You have done excellent application , But i am facing a problem that i m not able to enable the usermedia-screen-capture because when  I enter given url (chrome://flags/#enable-usermedia-screen-capture)  in chrome addressbar. i am not getting that 'enable screen capture support in getUserMedia()' option in that list. please suggest me how to resolve that or how to enable that. Currently i cant able to run your demo application because of the error. that says 
![screenshot from 2015-05-19 16 36 29](https://cloud.githubusercontent.com/assets/9369312/7701504/69240b38-fe45-11e4-8d83-b32014cf59ce.png)
![screenshot from 2015-05-19 16 32 14](https://cloud.githubusercontent.com/assets/9369312/7701522/a176068a-fe45-11e4-8a91-ab11ddd4860f.png)

please help me to resolve .
              thanks

**Comment by mgechev** [comment]
This library is deprecated. Take a look at the [readme](https://github.com/mgechev/jscapture#warning).

**Comment by fritx** [comment]
why? damn..

**Comment by mgechev** [comment]
Security concerns. However, chrome plugins allow access to this API.

**Comment by fritx** [comment]
Cool, have you done this nice job on a chrome plugin?

**Comment by mgechev** [comment]
Not yet but in case you're using plugin you're able to use NaCl and do not need the hacky solution for generation of webm.

**Comment by fritx** [comment]
:cheers:
